apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  nodeMaintenanceWindow:
    inProgress: true
    reusePVC: false
  enableSuperuserAccess: true

  storage:
    size: 1Gi
