apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5

  minSyncReplicas: 1
  maxSyncReplicas: 1

  nodeMaintenanceWindow:
    inProgress: true
    reusePVC: true

  replicationSlots:
    highAvailability:
      enabled: true

  storage:
    size: 500Mi
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.3"
    limits:
      memory: "512Mi"
      cpu: "0.3"
